#ifndef PROPERTYSHEET_GLOBAL_H
#define PROPERTYSHEET_GLOBAL_H

#include <QtCore/qglobal.h>

//#ifdef PROPERTYSHEET_LIB
//# define PROPERTYSHEET_EXPORT Q_DECL_EXPORT
//#else
//# define PROPERTYSHEET_EXPORT Q_DECL_IMPORT
//#endif
#define PROPERTYSHEET_EXPORT

#endif // PROPERTYSHEET_GLOBAL_H
